config/routes.rb
Switter::Application.routes.draw do
  resources :users
  resources :swits
  resources :comments

  post 'sweet' => 'swits#add_sweet'
  post 'sour' => 'swits#add_sour'
  post 'signin' => 'sessions#new'
  get 'signin' => 'sessions#new'
  post 'login' => 'sessions#create'

  resources :sessions, :only => [:new, :create, :destroy]

  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'tags' => 'swits#show_swit_tags'
  get 'home' => 'home#index'

  root 'sessions#new'

end

app/models/swit.rb
class Swit < ActiveRecord::Base
	belongs_to :user
	has_many :comment

	validates :content, :presence => true,
		:length => { minimum: 1, maximum: 140 },
		:uniqueness => { case_sensitive: false }
		
	def add_data(id, sweet, sour, tag)
		self.user_id = id
 		self.sweet = sweet
 		self.sour = sour
 		self.tag = tag;
	end
end

app/controllers/swits_controller.rb
class SwitsController < ApplicationController
  before_action :set_swit, only: [:show, :edit, :update, :destroy]

  # GET /swits
  # GET /swits.json
  def index
    @swits = Swit.all
    @user = User.find_by_id(session[:id])
  end

  # GET /swits/1
  # GET /swits/1.json
  def show
    @user = User.find_by_id(session[:id])
    @comments = Comment.all
    @comment = Comment.new
  end

  # GET /swits/new
  def new
    @swit = Swit.new
  end

  # GET /swits/1/edit
  def edit
    @user = User.find_by_id(session[:id])
  end

  # POST /swits
  # POST /swits.json
  def create
    @swit = Swit.new(swit_params)

    tags = ""
    door_tags = swit_params[:content].scan(/\{.+?\}/)

    door_tags.each do |x|
      tags = tags + x
    end

    @swit.add_data(session[:id], 0, 0, tags)
    respond_to do |format|
      if @swit.save
        format.html { redirect_to home_path }
        format.json { render action: 'show', status: :created, location: @swit }
      else
        format.html { render action: 'new' }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swits/1
  # PATCH/PUT /swits/1.json
  def update
    respond_to do |format|
      if @swit.update(swit_params)
        format.html { redirect_to @swit, notice: 'Swit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swits/1
  # DELETE /swits/1.json
  def destroy
    Comment.destroy_all(:swit_id => @swit.id)
    @swit.destroy
    respond_to do |format|
      format.html { redirect_to home_path }
      format.json { head :no_content }
    end
  end

  def add_sweet
    swit = Swit.find(params[:swit_id])
    swit.update(sweet: swit.sweet + 1)
    redirect_to home_path
  end

  def add_sour
    swit = Swit.find(params[:swit_id])
    swit.update(sour: swit.sour + 1)
    redirect_to home_path
  end

  def show_swit_tags
    @comments = Comment.all
    @comment = Comment.new
    @user = User.find_by_id(session[:id])
    @tag = params[:tag_value]

    @swits = Array.new
    @swits_array = Swit.all

    @swits_array.each do |swit|
      if swit.tag.include?(@tag)
        @swits.push(swit)
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swit
      @swit = Swit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swit_params
      params.require(:swit).permit(:user_id, :content, :sweet, :sour, :tag)
    end
end

app/helpers/swits_helper.rb
module SwitsHelper
end

app/views/swits/_form.html.haml
#type_swit_container
  = form_for @swit do |f|
    - if @swit.errors.any?
      #error_explanation
        %h2= "#{pluralize(@swit.errors.count, "error")} prohibited this swit from being saved:"
        %ul
          - @swit.errors.full_messages.each do |msg|
            %li= msg
    #swit_field
      = f.text_area :content, placeholder: 'Type your swit =)', maxlength: 140, required: true, title: 'Must be 1-140 characters.'
    #counter
    .actions
      = f.submit 'Swit', class: 'button'

app/views/swits/edit.html.haml
%h2#edit_swit_header Edit Swit

#edit_swit_container
  = form_for @swit do |f|
    - if @swit.errors.any?
      #error_explanation
        %h2= "#{pluralize(@swit.errors.count, "error")} prohibited this swit from being saved:"
        %ul
          - @swit.errors.full_messages.each do |msg|
            %li= msg
    #swit_field
      = f.text_area :content, placeholder: 'Type your swit =)', maxlength: 140, required: true, title: 'Must be 1-140 characters.'
    #counter
    .actions
      = f.submit 'Edit Swit', class: 'button'

app/views/swits/index.html.haml
%h1 Listing swits

%table
  %tr
    %th ID
    %th User
    %th Content
    %th Sweet
    %th Sour
    %th Tag
    %th
    %th
    %th

  - @swits.each do |swit|
    %tr
      %td= swit.id
      %td= swit.user_id
      %td= swit.content
      %td= swit.sweet
      %td= swit.sour
      %td= swit.tag
      %td= link_to 'Show', swit
      %td= link_to 'Edit', edit_swit_path(swit)
      %td= link_to 'Destroy', swit, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Swit', new_swit_path

app/views/swits/new.html.haml
%h1 New swit

= render 'form'

= link_to 'Back', swits_path

app/views/swits/show.html.haml
%h2#view_swit_header View Swit
#show_swit_container
  .swit
    .swit_username
      = User.find(@swit.user.id).username
    .swit_timestamp
      = @swit.created_at.strftime("%b %d, %Y  %I:%M")
      = puts (@swit.created_at.strftime("%H").to_i >= 12 ? "PM" : "AM")
    .sweets_sour_tally
      = "#{pluralize(@swit.sweet, "sweet")}"
      = "#{pluralize(@swit.sour, "sour")}"
    .swit_content
      = @swit.content
    .swit_category
      .sweet_button
        = form_tag sweet_path do
          = hidden_field_tag :swit_id, @swit.id
          = submit_tag 'Sweet', class: 'button'
      .sour_button
        = form_tag sour_path do
          = hidden_field_tag :swit_id, @swit.id
          = submit_tag 'Sour', class: 'button [secondary alert success]'
      .tag_container
        - tags = @swit.tag.scan(/\{.+?\}/)
        - tags.each do |tag|
          = form_tag tags_path do
            .tags
              = hidden_field_tag :tag_value, tag
              = submit_tag tag
      .user_swit_options
        - if @swit.user.id == session[:id]
          = link_to 'Edit', edit_swit_path(@swit)
          = link_to 'Delete', @swit, :method => :delete, :data => { :confirm => 'Are you sure?' }
        .comments
          - @comments.each do |swit_comment|
            - if swit_comment.swit.id == @swit.id
              .comment
                %strong
                  = User.find_by_id(Swit.find_by_id(@swit.id).user_id).username + ":"
                %text.comment_content
                  = swit_comment.content
                .comment_timestamp
                  = swit_comment.created_at.strftime("%b %d, %Y  %I:%M")
          = form_for @comment do |f|
            .field
            = f.text_area :content, placeholder: 'Type your comment.', maxlength: 140, required: true, title: 'Must be 1-140 characters.'
            = f.hidden_field :swit_id, value: @swit.id
            = f.submit 'Comment', class: 'small button'
        .view_comment_label Comments

app/views/swits/show_swit_tags.html.haml
%h2#door_tag_header 
	= "Showing swits with \"" + @tag + "\" door tag."
#swits_tag
	= render 'includes/swits'